### ISSUE TITLE
Cannot install on 18.04

### ISSUE THREAD

**Issue by vmajor** [JarbasAl/jarbas-core#4]
Collecting py_msm (from -r requirements.txt (line 43))
  Could not find a version that satisfies the requirement py_msm (from -r requirements.txt (line 43)) (from versions: )
No matching distribution found for py_msm (from -r requirements.txt (line 43))

mycroft dev branch installed correctly and runs well

**Comment by JarbasAl** [comment]
[py_msm](https://github.com/JarbasAl/ZZZ-py_msm) no longer exists, it is now officially part of mycroft

this fork is quite outdated, i will get it back in shape soon but meanwhile consider using mycroft-core
